version: 2
jobs:
  build:
    docker:
      - image: ubuntu:focal
    environment:
      - DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y sudo git gcc g++ clang build-essential cmake bash curl uuid-dev && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Fetch submodules
          command: 'git submodule update --init --recursive'
      - run:
          name: Build and run tests with code coverage enabled
          command: 'bash -eo pipefail test.sh cov'
      - run:
          name: Upload coverage reports
          when: on_success
          command: cd build/CMakeFiles/cecies.dir/src && bash <(curl -s https://codecov.io/bash)
